name: EverNifeCore
version: 2.0.1.6
author: EverNife
main: br.com.finalcraft.evernifecore.EverNifeCore
softdepend: [ WorldGuard, WorldEdit, GriefPreventionPlus , LuckPerms, Vault, MVdWPlaceholderAPI, Factions, GPPSkyBlock, PlaceholderAPI, ProtocolLib]
loadbefore: [ BossShopPro ]