name: EverNifeCore
version: 2.0.2.1
author: EverNife
main: br.com.finalcraft.evernifecore.EverNifeCore
softdepend: [ WorldGuard, WorldEdit, GriefPreventionPlus , LuckPerms, Vault, MVdWPlaceholderAPI, Factions, GPPSkyBlock, PlaceholderAPI, ProtocolLib]
loadbefore: [ BossShopPro ]
api-version: 1.13