version 'dont-matter' // never published; bundled into the minecraft shadow jar

repositories {
    maven {
        name = 'spigotmc-repo'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots'
    }
}

dependencies {
    compileOnly project(':common')

    compileOnly libs.spigot.api

    compileOnly name: "GriefPreventionPlus-13.3"
    compileOnly name: "PlaceholderAPI-2.11.2"
    compileOnly name: "worldguard-bukkit-7.0.5-dist" // up to 1.16
    compileOnly name: "worldedit-bukkit-7.2.5-dist"  // up to 1.16

    compileOnly libs.commons.lang3.legacy
}
