version 'dont-matter' // never published; bundled into the minecraft shadow jar

repositories {
    maven {
        name = 'spigotmc-repo'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots'
    }
}

dependencies {
    compileOnly project(':common')

    implementation project(':minecraft:modules:VersionedPlugins')
    compileOnly libs.spigot.api

    compileOnly name: "worldguard-bukkit-7.0.5-dist" // up to 1.16
    compileOnly name: "worldedit-bukkit-7.2.5-dist"  // up to 1.16
}
