version 'dont-matter' // never published; bundled into the minecraft shadow jar

repositories {
    maven {
        name = 'spigotmc-repo'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots'
    }
}

dependencies {
    compileOnly project(':common')

    implementation project(':minecraft:modules:VersionedPlugins')
    compileOnly libs.bukkit

    compileOnly name: "worldguard-bukkit-6.2.2"
    compileOnly name: "worldedit-bukkit-6.0"
}
